### ISSUE TITLE
error: Too many arguments to return

### ISSUE THREAD

**Issue by band1k1** [adonley/ethereum-brute-force#1]
After launch displayed an error

# command-line-arguments
.\main.go:132:2: too many arguments to return
        have (*ecdsa.PrivateKey, error)
        want (*ecdsa.PrivateKey)

**Comment by Elecman** [comment]
How fix that problem?

**Comment by adonley** [comment]
Will take a look tonight - do you guys have a list of all the addresses with balances at hand? It requires to load this into memory to be faster than the JSON-RPC calls to a node.

**Comment by band1k1** [comment]
Sure, I tried to launch with list of some addresses with balances "./balances.csv" - same error.

**Comment by adonley** [comment]
Fixed. Did I upload balances.csv? That must be outdated by now.
