### ISSUE TITLE
update arg not working ?

### ISSUE THREAD

**Issue by ghost** [adonley/ethereum-brute-force#2]
am trying to update the addresses list using the update=true, geth is running and RPC is working at port 8545, it just start to search, also i noticed the seed addr are always the same each time i run it.

> go run main.go -update=true -provider=http://localhost:8545
2018/05/12 21:51:10 Number of addresses loaded: 27564635
2018/05/12 21:51:10 Seed addr: [33 15 199 187 129 134 57 172 72 164 198 175 162 241 88 26 139 149 37 226 15 218 104 146 127 43 47 248 54 247 53 120]
2018/05/12 21:51:10 Seed addr: [219 15 165 76 41 247 253 146 141 146 202 67 241 147 222 228 127 89 21 73 245 151 168 17 200 250 103 171 3 30 189 156]
2018/05/12 21:51:10 Seed addr: [106 164 233 130 159 34 75 232 234 246 103 38 201 7 124 180 31 121 1 157 137 43 233 147 3 178 190 88 130 243 36 7]
2018/05/12 21:51:10 Seed addr: [88 163 141 126 65 39 219 253 71 122 50 245 254 112 138 41 191 6 40 1 195 249 87 118 62 234 13 175 98 214 93 206]
2018/05/12 21:51:10 Seed addr: [91 165 36 247 53 142 251 181 184 50 32 207 88 99 108 188 64 207 172 154 235 60 200 71 188 220 241 15 113 122 162 98]
2018/05/12 21:51:10 Seed addr: [119 255 10 58 14 199 62 16 255 64 142 206 135 40 248 74 225 175 123 191 134 233 148 111 176 143 182 88 151 90 181 82]
2018/05/12 21:51:10 Seed addr: [157 112 64 116 175 74 200 192 245 164 111 9 110 232 71 122 119 84 48 3 143 192 14 172 3 175 77 220 211 37 189 43]
2018/05/12 21:51:11 Checked: 23722, Speed: 23721 per second
2018/05/12 21:51:12 Checked: 49157, Speed: 25420 per second

**Comment by nostradam** [comment]
I got the same question, have you found a way ?

**Comment by adonley** [comment]
No longer need the update argument in latest version.
