### ISSUE TITLE
win 10

### ISSUE THREAD

**Issue by spider703** [adonley/ethereum-brute-force#3]
can i ask to make this program to run on Windows 10 in exe file

**Comment by koceila1991** [comment]
Hi spider,

It is wrriten in jscript languages, It can work in Windows 10 but you need to install nodejs et depencies but at this time i  haven't time to make it as an exe file.

**Comment by adonley** [comment]
I moved off of github because windows bought it.

**Comment by spider703** [comment]
and where to find your repositories now?
